### ISSUE TITLE
5: 2D Ising Metropolis Performance

### ISSUE THREAD

**Issue by fortysixandtwo** [ponderstibbons/simphys15-16#1]
Looking to the next sheet, where we'd like to improve performance in order to be able to simulate bigger systems efficiently I wanted to mention that the energy for each generated sample is getting recalculated repeatedly.
It would be better to just calculate the difference in energy due to the trial move (flipping a random spin)  as it's computationally cheaper.

**Comment by pmrv** [comment]
I just checked the provided templates and they basically do just that, so I'll base all new work for the next sheet on those.

**Comment by fortysixandtwo** [comment]
Ez pz!
